# instance_url should be Plextrac instance URL i.e. https://example.plextrac.com
instance_url: 
username: 
password: 

csv_headers_file_path: header_mapping.csv
csv_data_file_path: 

# name of plugin you want to import parser actions to. pick from list. must already exist in your PT instance
# acunetix
# burp
# burphtml
# coreimpact
# nessus
# invicti
# netsparker
# nexpose
# nipper
# nmap
# openvas
# ptrac
# qualys
# rapidfire
# scythe
# veracode
# pentera
# checkmarx
# hclappscan
# nodezero
# owaspzap
# nodeware
parser_id: 
